User.create!([
  {email: "a@a.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2014-11-16 11:03:49", last_sign_in_at: "2014-11-15 10:48:12", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "A A"},
  {email: "b@b.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2014-11-16 11:59:35", last_sign_in_at: "2014-11-15 10:44:58", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "B B"},
  {email: "c@c.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2014-11-16 12:24:09", last_sign_in_at: "2014-11-16 12:04:12", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "C C"},
  {email: "d@d.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2014-11-16 12:23:50", last_sign_in_at: "2014-11-16 12:06:50", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "D D"},
  {email: "e@e.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2014-11-16 12:25:32", last_sign_in_at: "2014-11-16 12:24:22", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "E E"},
  {email: "f@f.com", password: "a", password_confirmation: "a", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2014-11-16 12:26:18", last_sign_in_at: "2014-11-16 12:21:17", current_sign_in_ip: "73.2.50.30", last_sign_in_ip: "73.2.50.30", name: "F F"}
])
Image.create!([
  {filename: "ZE0p0TN-1jMe2njTN8y8xQ.jpg", public: true, user_id: 6},
  {filename: "8AYUaAk-q8R9u-pu5UVcRQ.jpg", public: true, user_id: 6},
  {filename: "x6O1WKRUI3D0b_VlkOiX9Q.jpg", public: true, user_id: 6},
  {filename: "kpVulv-TL4QI3HvfVszETg.jpg", public: false, user_id: 6},
  {filename: "Ejg-L_JOaaf_K_uE1ipCEg.jpg", public: false, user_id: 6},
  {filename: "DQVMOd8VkdvPFYxzyb-oLg.jpg", public: false, user_id: 6},
  {filename: "-_w27nDLg8AZDuHXkQnS0g.jpg", public: false, user_id: 6},
  {filename: "Bw3J5EY6i57e_5P3VwZKew.jpg", public: false, user_id: 6},
  {filename: "lhtuQuBh_4y8IHIc9nclWw.jpg", public: false, user_id: 6},
  {filename: "4njnsIrnoX3xgdZBZlbXBg.jpg", public: false, user_id: 6},
  {filename: "4YdKFS4cM2tbvhAB1xP04g.jpg", public: false, user_id: 1},
  {filename: "ZQvl_COuD0zj7X8Ilb0NwA.jpg", public: true, user_id: 1},
  {filename: "sut2-2bqh2qEsCTaWnDMTg.jpg", public: true, user_id: 1},
  {filename: "H_bjY-TKftU-UsdIIjMJng.jpg", public: true, user_id: 1},
  {filename: "HsRXOJ_BAFAFS5MLFqgfDg.jpg", public: false, user_id: 1},
  {filename: "AFO8Jt-1h9MljdJ-DtubSQ.jpg", public: false, user_id: 1},
  {filename: "9tflUQ-CJ9TvwyrUcDP0oQ.jpg", public: false, user_id: 1},
  {filename: "Ckj-lYfiz6qqJqbEXd9MRg.jpg", public: false, user_id: 1},
  {filename: "55T4sri_GHA2d-JH31b_2A.jpg", public: false, user_id: 1},
  {filename: "a7lpXAI6XX1-lasjXDaMAw.jpg", public: false, user_id: 1},
  {filename: "QH9xUxEk94ppEhc5dUnFrQ.jpg", public: true, user_id: 2},
  {filename: "kgqtOdHU_JRhOmd8Zt_JLA.jpg", public: true, user_id: 2},
  {filename: "j7FFhTsUH82FJjuKL1aa6Q.jpg", public: false, user_id: 2},
  {filename: "yNHxVET5TRpXXObehYf-fA.jpg", public: false, user_id: 2},
  {filename: "hbgOQ_9Bpf7MfktRhCoG4A.jpg", public: false, user_id: 2},
  {filename: "Nxh9NTKBfWx3lnc8xFFZaw.jpg", public: false, user_id: 2},
  {filename: "-cp4c0F-O1ZLBc-Cyyp6uA.jpg", public: false, user_id: 2},
  {filename: "d44EJQsJpxlh7WbGgc9LYQ.jpg", public: false, user_id: 2},
  {filename: "wm7iU3LLlA4SVdNO8qnL6Q.jpg", public: false, user_id: 2},
  {filename: "M9kLNrnXYw09SU_kdGXjug.jpg", public: true, user_id: 3},
  {filename: "FGtL-d6-9WsqxmZ4nOtYog.jpg", public: true, user_id: 3},
  {filename: "BxAfNBMRR-Ezxaj3ZURC7Q.jpg", public: false, user_id: 3},
  {filename: "G1RcPrV_6LwFcRYMFdgv6g.jpg", public: false, user_id: 3},
  {filename: "XSbAzkYNKel06gCW5bBlUg.jpg", public: false, user_id: 3},
  {filename: "U33m5l3MEfbd5v55zLCiGA.jpg", public: false, user_id: 3},
  {filename: "crQL-tcYGGBYOHAd4sUidA.jpg", public: false, user_id: 3},
  {filename: "te6F47JsICimeSaZ1VbcgA.jpg", public: false, user_id: 3},
  {filename: "V_NUlnhSP7IoMF6CeoWosg.jpg", public: false, user_id: 3},
  {filename: "VbNv7QanFuExHOSAsUHbtQ.jpg", public: true, user_id: 4},
  {filename: "h4IWZYjKvi1-zTsifJw4jA.jpg", public: true, user_id: 4},
  {filename: "llQjcE9pDblIRtZ8wHdoaw.jpg", public: false, user_id: 4},
  {filename: "Fm41jOXtn3KngMV-A2qIRQ.jpg", public: false, user_id: 4},
  {filename: "YVbr2gp16zTMyJnHo97T3A.jpg", public: false, user_id: 4},
  {filename: "jaWmq7kyak8VboqMAaCywg.jpg", public: false, user_id: 4},
  {filename: "L6b1XzdNuO8ankX1HnZyew.jpg", public: false, user_id: 4},
  {filename: "V1CQMn1ivY0uFzMbJYXK6Q.jpg", public: false, user_id: 4},
  {filename: "a7YQogWUzFX6J7jaNDJZng.jpg", public: false, user_id: 4},
  {filename: "8dfZLamkeYWVShfHcpSjhQ.jpg", public: true, user_id: 5},
  {filename: "Af_qbGlQQYPlw32Bjd0OEQ.jpg", public: true, user_id: 5},
  {filename: "rk2Yb2wEeJHEvgL6V9qJbw.jpg", public: false, user_id: 5},
  {filename: "-z6EowL7s8qKoQuzQhvVZQ.jpg", public: false, user_id: 5},
  {filename: "bfFr1Eo-SD4e02hySJNkFA.jpg", public: nil, user_id: 5},
  {filename: "U7PoKEGWI_-Ej-I955aZAQ.jpg", public: false, user_id: 5}
])
Imageuser.create!([
  {user_id: 1, image_id: 6},
  {user_id: 2, image_id: 6},
  {user_id: 5, image_id: 30},
  {user_id: 6, image_id: 30},
  {user_id: 6, image_id: 33},
  {user_id: 1, image_id: 33},
  {user_id: 2, image_id: 46},
  {user_id: 3, image_id: 46},
  {user_id: 3, image_id: 54},
  {user_id: 4, image_id: 54},
  {user_id: 3, image_id: 8},
  {user_id: 4, image_id: 8},
  {user_id: 1, image_id: 8},
  {user_id: 2, image_id: 8},
  {user_id: 1, image_id: 8},
  {user_id: 5, image_id: 8},
  {user_id: 5, image_id: 18},
  {user_id: 6, image_id: 18},
  {user_id: 1, image_id: 29},
  {user_id: 3, image_id: 29},
  {user_id: 4, image_id: 29},
  {user_id: 5, image_id: 29},
  {user_id: 6, image_id: 29},
  {user_id: 2, image_id: 33},
  {user_id: 4, image_id: 33},
  {user_id: 5, image_id: 33},
  {user_id: 1, image_id: 43},
  {user_id: 2, image_id: 43},
  {user_id: 3, image_id: 43},
  {user_id: 5, image_id: 43},
  {user_id: 6, image_id: 43},
  {user_id: 1, image_id: 56},
  {user_id: 2, image_id: 56},
  {user_id: 3, image_id: 56},
  {user_id: 4, image_id: 56},
  {user_id: 6, image_id: 56},
  {user_id: 1, image_id: 37},
  {user_id: 4, image_id: 37},
  {user_id: 6, image_id: 37},
  {user_id: 3, image_id: 18},
  {user_id: 1, image_id: 26},
  {user_id: 3, image_id: 26},
  {user_id: 4, image_id: 26},
  {user_id: 1, image_id: 36},
  {user_id: 6, image_id: 36},
  {user_id: 4, image_id: 36},
  {user_id: 2, image_id: 39},
  {user_id: 4, image_id: 39},
  {user_id: 5, image_id: 39},
  {user_id: 1, image_id: 48},
  {user_id: 5, image_id: 48},
  {user_id: 1, image_id: 55},
  {user_id: 2, image_id: 55},
  {user_id: 3, image_id: 55},
  {user_id: 4, image_id: 55},
  {user_id: 6, image_id: 55}
])
Tag.create!([
  {msg: "Tag from F", image_id: 8},
  {msg: "Tag from A", image_id: 18},
  {msg: "Tag from B", image_id: 29},
  {msg: "Tag from C", image_id: 33},
  {msg: "Tag from D", image_id: 43},
  {msg: "Tag from  E", image_id: 56},
  {msg: "Tag from C", image_id: 43},
  {msg: "Another tag from C", image_id: 43},
  {msg: "Dianna Troy at her finest", image_id: 18},
  {msg: "DEEERRRPPPP!", image_id: 15},
  {msg: "Jek Derpins, get out of there!", image_id: 15},
  {msg: "I met her ex husband, Bob Turr.  He said that between her coke use and psychosis being married to her wasn't anywhere as cool as I had imagined when I was a kid", image_id: 16},
  {msg: "I work at a Mexican restaurant.  I make this face a few hours after eating too much food at work.", image_id: 20},
  {msg: "Life gave him lemons.  We've all been there, metaphorically", image_id: 19},
  {msg: "I'm pretty sure the world has gone all spinny like that for me, too, after receiving a fresh, steaming pile of lemons from life.", image_id: 19},
  {msg: "One of the greatest action stars of the last few generattions", image_id: 24},
  {msg: "Until very recently he did all of his own stunts.  Watching the outtakes at the end of his films is hillarious.", image_id: 24},
  {msg: "Did you know that the name of this film was supposed to me Meals on Wheels, but he previous 2 films had titles starting with M and neither had done very well, so they switched it arround, thinking that the leading M was unlucky.", image_id: 24},
  {msg: "I hated him until I saw Navigator ... or whatever that film in which he played the guys who built the Spruce Goose.", image_id: 26},
  {msg: "You know, the crazy reclusive mysophobic guy", image_id: 26},
  {msg: "Why is this woman on TV again?", image_id: 27},
  {msg: "Seriously, why?", image_id: 27},
  {msg: "Why do I even have to know her name?", image_id: 27},
  {msg: "He tries to act all tough", image_id: 36},
  {msg: "but you know that, deep down, he really does care", image_id: 36},
  {msg: "Ah, the time honored \"Pile Driver\"", image_id: 37},
  {msg: "I like how he's still smiling.", image_id: 37},
  {msg: "Fuck this guy.", image_id: 39},
  {msg: "No really.", image_id: 39},
  {msg: "No, fuck the director of the movie.  Way to ruin Spiderman, jackass.", image_id: 39},
  {msg: "WTF?", image_id: 45},
  {msg: "They didn't even have to touch up the image much", image_id: 45},
  {msg: "There are whole weeks of my life where I suspect this was how I actied", image_id: 43},
  {msg: "Oh Derp, Where art thou?", image_id: 44},
  {msg: "Derps 11", image_id: 44},
  {msg: "ER Dr. Derp", image_id: 44},
  {msg: "NOM!", image_id: 46},
  {msg: "Yeah, some things doon't translate too well.", image_id: 48},
  {msg: "The internets are full of humorous, poorly translated signs and packages.", image_id: 48},
  {msg: "I used to skate when I was kid.", image_id: 56},
  {msg: "The kids now call this \"The Scorpion\" or \"Scorpioning\"", image_id: 56},
  {msg: "I pray to any and every god there is, ever was, or will be that I am in a meeting that is interrupted my flying dildos!", image_id: 55},
  {msg: "No, really, when it comes to the theater of the obsurd, it doesn't get much better than this.", image_id: 55}
])
