# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 062e41ca69655f0f145800ffe24c019ca90006c01e5998c23d8d17dbc84b84006e73c8446bbc8a518d94a8b37fa63a1786772798107eb97fab834613e14c303b

production:
  secret_key_base: 63818e682b7fd221be3482ed6eb025661898c1ce43c992a536a369b989dc66eb5c15106398605b4a254ba24ca192667f43635ee5f68269e60299e9727003b2db

test:
  secret_key_base: 8378efefd8ef6c6f603bf32ef61256fc7d3b38461137253db2a2704853d7261582cf573579d2559cfd976b5ad0e41b453dbae06c7b7f60bf2e5dddb08e5e5631

# Do not keep production secrets in the repository,
# instead read values from the environment.
#production:
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
